using UnityEngine;

public class HealPotion : MonoBehaviour
{
    [SerializeField] private AudioClip collectSound; // ğŸ”Š ì‚¬ìš´ë“œ í´ë¦½ ì—°ê²°ìš©

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
    
    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            PlayerController player = other.GetComponent<PlayerController>();
            if (player != null)
            {
                player.Heal(1); // ì²´ë ¥ 1 íšŒë³µ
            }
            if (collectSound != null)
                AudioSource.PlayClipAtPoint(collectSound, Camera.main.transform.position);

            Destroy(gameObject); // í¬ì…˜ ì‚¬ë¼ì§
        }
    }
}
